//#if MC >= 1.21 && MC <= 26.2
package carpet.fga;

import com.sun.net.httpserver.HttpServer;
import com.sun.net.httpserver.HttpExchange;
import net.minecraft.server.MinecraftServer;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;

/** Loopback-only, read-only diagnostics. It intentionally has no command or write endpoint. */
public final class FakePlayerItemSortDashboard {
    private static HttpServer http; private static int port;
    private FakePlayerItemSortDashboard() {}
    public static synchronized void start(MinecraftServer server,int requested) {
        if(http!=null&&port==requested)return; stop(); try { http=HttpServer.create(new InetSocketAddress("127.0.0.1",requested),0);port=requested;
            http.createContext("/api/cache", FakePlayerItemSortDashboard::writeInventoryCache);
            http.createContext("/api/v1/inventory", FakePlayerItemSortDashboard::writeInventoryCache);
            http.createContext("/", e->{byte[] body=PAGE.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type","text/html; charset=utf-8");e.sendResponseHeaders(200,body.length);try(var out=e.getResponseBody()){out.write(body);}});http.setExecutor(null);http.start();
        } catch(IOException ignored) { http=null; }
    }
    public static synchronized void stop(){if(http!=null){http.stop(0);http=null;}port=0;}
    public static synchronized String status(){return http==null?"stopped":"http://127.0.0.1:"+port+"/";}
    /** Stable, loopback-only client-mod API. It serves the already-built memory snapshot only. */
    private static void writeInventoryCache(HttpExchange exchange) throws IOException {
        if (!"GET".equals(exchange.getRequestMethod())) { exchange.sendResponseHeaders(405, -1); return; }
        byte[] body = FakePlayerItemSortManager.dashboardJson().getBytes(StandardCharsets.UTF_8);
        exchange.getResponseHeaders().set("Content-Type", "application/json; charset=utf-8");
        exchange.getResponseHeaders().set("Access-Control-Allow-Origin", "*");
        exchange.getResponseHeaders().set("Cache-Control", "no-store");
        exchange.sendResponseHeaders(200, body.length);
        try (var out = exchange.getResponseBody()) { out.write(body); }
    }
    private static final String PAGE = """
        <!doctype html><html lang=zh-CN><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1">
        <title>FGA 分类库存</title><style>
        :root{color-scheme:dark;--bg:#111816;--panel:#17231f;--line:#30443b;--text:#edf3ee;--muted:#9aac9f;--mint:#67d5a1;--cyan:#54c7ce;--amber:#e7bc61}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px system-ui,"Microsoft YaHei",sans-serif}main{max-width:1280px;margin:auto;padding:32px 22px 56px}.mast{border:1px solid var(--line);background:#18251f;padding:30px 32px;display:flex;justify-content:space-between;gap:24px;align-items:flex-end}.eyebrow{color:var(--mint);font-size:12px;margin-bottom:8px}h1{font-size:30px;line-height:1;margin:0}p{margin:9px 0 0;color:var(--muted)}.update{text-align:right;color:var(--muted);font-variant-numeric:tabular-nums}.dot{display:inline-block;width:8px;height:8px;background:var(--mint);margin-right:7px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:20px 0}.stat{border:1px solid var(--line);padding:17px;background:var(--panel)}.stat span{display:block;color:var(--muted);margin-bottom:8px}.stat b{font-size:27px;color:var(--mint);font-variant-numeric:tabular-nums}.workspace{border:1px solid var(--line);background:#15201b}.bar{padding:18px 20px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:16px}.bar h2{font-size:17px;margin:0}.search{width:min(390px,100%);padding:11px 13px;background:#0e1713;border:1px solid #40574b;color:var(--text);font:inherit}.meta{padding:11px 20px;color:var(--muted);border-bottom:1px solid var(--line);font-size:12px}table{width:100%;border-collapse:collapse}th,td{padding:13px 20px;border-bottom:1px solid #27382f;text-align:left}th{font-size:12px;color:var(--muted);font-weight:600;background:#19271f}tr:hover td{background:#1b2a23}.item{font-weight:600}.route{color:var(--cyan);font-family:ui-monospace,Consolas,monospace;font-size:12px}.actions{width:156px;white-space:nowrap}.copy{padding:6px 8px;background:#0e1713;border:1px solid #40574b;color:var(--mint);font:12px ui-monospace,Consolas,monospace;cursor:pointer}.copy+.copy{margin-left:6px}.copy:hover,.copy:focus-visible{background:#22372c;border-color:var(--mint);outline:none}.num{text-align:right;font-variant-numeric:tabular-nums;font-size:16px}.last{color:var(--amber);font-family:ui-monospace,Consolas,monospace;font-size:12px}#error{min-height:20px;padding:10px 20px;color:#ffb4a8;font-size:12px}@media(max-width:720px){main{padding:16px 10px}.mast{padding:24px 20px;display:block}.update{text-align:left;margin-top:18px}.stats{grid-template-columns:repeat(2,1fr)}.bar{display:block}.search{margin-top:14px}th:nth-child(3),td:nth-child(3){display:none}th,td{padding:12px}.actions{width:134px}.copy{padding:6px}}
        </style><main><header class=mast><div><div class=eyebrow>FGA / STORAGE INDEX</div><h1>分类库存</h1><p>按物品检索分类假人及后位占用情况</p></div><div class=update><span class=dot></span>本地只读面板<br><span id=updated>正在读取数据</span></div></header><section class=stats id=stats></section><section class=workspace><div class=bar><h2>物品目录</h2><div><select id=lang class=search><option value=server>跟随服务器</option><option value=chinese>中文</option><option value=english>English</option><option value=custom>自定义</option></select><label class=muted><input type=checkbox id=hideZero checked> 隐藏 0 库存</label><input class=search id=q placeholder="搜索物品名称或分类假人" autofocus></div></div><div class=meta id=meta>正在加载分类缓存</div><table><thead><tr><th class=actions>操作</th><th>物品</th><th>分类假人</th><th class=num>总数量</th><th>最后使用后位</th></tr></thead><tbody id=rows></tbody></table><div id=error></div></section></main>
        <script>
        let data={items:[]},stamp='';const q=document.querySelector('#q'),lang=document.querySelector('#lang'),hideZero=document.querySelector('#hideZero'),rows=document.querySelector('#rows'),stats=document.querySelector('#stats'),error=document.querySelector('#error'),meta=document.querySelector('#meta'),updated=document.querySelector('#updated');const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
        function nameOf(x){return (x.names||{})[lang.value]||(x.names||{}).server||''}function grouped(){const result=new Map();for(const raw of data.items||[]){const name=nameOf(raw),key=name+'\u0000'+raw.target,previous=result.get(key)||{name,target:raw.target,count:0,lastIndex:-1};previous.count+=Number(raw.count||0);previous.lastIndex=Math.max(previous.lastIndex,Number(raw.lastIndex??-1));result.set(key,previous)}return [...result.values()]}async function copyCommand(target,action,button){const command='/player '+target+' '+action;try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(command);else{const area=document.createElement('textarea');area.value=command;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();document.execCommand('copy');area.remove()}const label=button.textContent;button.textContent='已复制';setTimeout(()=>button.textContent=label,1200)}catch(e){error.textContent='无法复制命令：'+command}}function render(){const needle=q.value.trim().toLowerCase(),items=grouped().filter(x=>(!hideZero.checked||x.count>0)&&(x.name+' '+x.target).toLowerCase().includes(needle));stats.innerHTML=`<div class=stat><span>已索引物品</span><b>${data.cacheEntries||0}</b></div><div class=stat><span>活跃分类任务</span><b>${data.jobs||0}</b></div><div class=stat><span>待处理队列</span><b>${(data.queued||0)+(data.rebuildQueued||0)}</b></div><div class=stat><span>搜索结果</span><b>${items.length}</b></div>`;meta.textContent=`显示 ${items.length} 个聚合分类项`;rows.innerHTML=items.map(x=>{const last=x.lastIndex<0?'尚未创建':x.lastIndex===0?'首位':x.target+'_'+x.lastIndex;const target=esc(x.target);return `<tr><td class=actions><button class=copy data-action=spawn data-target="${target}" title="复制 /player ${target} spawn">spawn</button><button class=copy data-action=inventory data-target="${target}" title="复制 /player ${target} inventory">inventory</button></td><td class=item>${esc(x.name)}</td><td class=route>${target}</td><td class=num>${Number(x.count||0).toLocaleString()}</td><td class=last>${esc(last)}</td></tr>`}).join('')||'<tr><td colspan=5 class=meta>没有匹配的分类物品</td></tr>';rows.querySelectorAll('.copy').forEach(button=>button.addEventListener('click',()=>copyCommand(button.dataset.target,button.dataset.action,button)));error.textContent=data.lastError||'';updated.textContent='最近更新：'+stamp}
        async function refresh(){try{data=await (await fetch('/api/v1/inventory',{cache:'no-store'})).json();stamp=new Date().toLocaleTimeString();render()}catch(e){error.textContent='无法读取 dashboard 数据：'+e.message}}q.addEventListener('input',render);lang.addEventListener('change',render);hideZero.addEventListener('change',render);refresh();setInterval(refresh,2000);
        </script>""";
}
//#endif
